### ISSUE TITLE
How to fix the DM has control of your centering?

### ISSUE THREAD

**Issue by mrjaksauce** [SDoehren/always-centred#1]
All I get is that notification. Where is the option to turn off DM control?

**Comment by SDoehren** [comment]
That shouldn't be active.  I have pushed a hot fix that should resolve the issue; please update and confirm.

**Comment by mrjaksauce** [comment]
Notes:

Updated. Still have the same issue.
Tested using just always-centred and nothing else to make sure there is nothing interfering. Still the same issue.
It did update via the normal way, but I after the above didn't work I removed and re-installed the module just in case it didn't update correctly. Still the same issue.
Tested with each both Party View and Selected. Also tested with and without Zoom view. Still the same issue.

Is there any other testing I can do to help?

Other things noted when module enabled for DM and Players:
When the player side moves the token, and the DM has the **same** token selected, the view moves on the DM screen. 
Question: Is there a way to make this functionality optional? I.e. If DM has same token selected as player, and the player moves the token, don't move the DM screen.

**Comment by SDoehren** [comment]
Ended up being a couple of fixes, the current version is 0.1.4

**Comment by mrjaksauce** [comment]
All fixed! You are awesome :)

**Comment by SDoehren** [comment]
Sorry, complete screw up at my end.  

The issue is this release has some code for a future release and there was a typo in one of the default values for a hidden variable.

**Comment by SDoehren** [comment]
O, great, I'm glad.  

And thank you.
